SELECT 
    *
FROM
    supply_chain_data_analysis;


-- 1. Find the top products with the highest total revenue.
CREATE TABLE top_productswiththe_higestrevenue AS SELECT Product_type,
    MAX(Revenuegenerated) AS top_10_Revenue_Generated FROM
    supply_chain_data_analysis
GROUP BY Product_type;


-- 2.List all products where stock levels are below 10.
CREATE TABLE stock_level AS SELECT * FROM
    supply_chain_data_analysis
WHERE
    Stocklevels < 10
ORDER BY Stocklevels;


-- 3.Calculate total revenue generated by each customer demographic group.
CREATE TABLE revenue_by_eachcustomer AS SELECT Customerdemographics,
    SUM(Revenuegenerated) AS Total_Revenue_Generatedby_each_customer FROM
    supply_chain_data_analysis
GROUP BY Customerdemographics;


-- 4. Find the total number of products sold for each product type.
CREATE TABLE total_numberof_products_sold AS SELECT Product_type,
    COUNT(Number_ofproductssold) AS Total_number_of_products_sold FROM
    supply_chain_data_analysis
GROUP BY Product_type;


-- 5.List products with lead times greater than 20 days.
CREATE TABLE greater_leadtime AS SELECT * FROM
    supply_chain_data_analysis
WHERE
    Leadtimes > 20
ORDER BY Leadtime;


-- 6.Identify products where manufacturing cost is more than 50% of the selling price.
CREATE TABLE manufacture_cost AS SELECT * FROM
    supply_chain_data_analysis
WHERE
    Manufacturing_costs > 0.5 * Price;
    
    
 -- 7.Find the average order quantity for each location.
CREATE TABLE avg_order_quantity AS SELECT Location, AVG(Orderquantities) AS Avg_Order_Quantities FROM
    supply_chain_data_analysis
GROUP BY Location;
 
 
 -- 8. Count how many products used each transportation mode (Road, Air, Rail).
CREATE TABLE find_transportation_mode AS SELECT Transportationmodes, COUNT(Product_type) FROM
    supply_chain_data_analysis
GROUP BY Transportationmodes;


-- 9. List all products where defect rates are greater than 5%.
CREATE TABLE find_defect_rate AS SELECT * FROM
    supply_chain_data_analysis
WHERE
    Defectrates > 0.5;
    
-- 10. Show all products where the inspection result is "Fail".
CREATE TABLE find_the_inspectionresult AS SELECT Product_type, Inspectionresults FROM
    supply_chain_data_analysis
WHERE
    Inspectionresults = 'fail';
    
-- 11. Calculate total transportation cost grouped by route (Route A, B, C).
CREATE TABLE find_the_totaltransporatation AS SELECT Routes, SUM(Costs) FROM
    supply_chain_data_analysis
GROUP BY Routes
ORDER BY Routes;

-- 12. Identify products with production volumes OVER 100 but order quantities UNDER  50.
CREATE TABLE find_the_volums_quantitites AS SELECT Product_type, Production_volumes, Orderquantities FROM
    supply_chain_data_analysis
WHERE
    Production_volumes > 100
        AND Orderquantities < 50;

-- 13. calculate the total revenue generated by each product type (skincare, haircare).
CREATE TABLE find_the_totalrevenue AS SELECT Product_type, SUM(Revenuegenerated) FROM
    supply_chain_data_analysis
WHERE
    Product_type IN ('skincare' , 'haircare')
GROUP BY Product_type;

-- 14. List all products with availability above 80 but number of products sold below 50.
CREATE TABLE find_the_availability AS SELECT Product_type, Stocklevels, Number_ofproductssold FROM
    supply_chain_data_analysis
WHERE
    Stocklevels > 80
        AND Number_ofproductssold < 50;
        
-- 15. Compute the average lead time for each product type
CREATE TABLE avg_leadtime_foreach_product AS SELECT Product_type, AVG(Leadtimes) AS Lead_Timefor_eachproduct FROM
    supply_chain_data_analysis
GROUP BY Product_type;

